#!/bin/bash
# Source https://github.com/cadorn/bash.origin
. "$HOME/.bash.origin"
function init {
	eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
	BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
	local __BO_DIR__="$___TMP___"


	function runJSTests {
		pushd "$__BO_DIR__/.." > /dev/null
			if [ ! -e "node_modules/.bin/mocha" ]; then
				BO_run_npm install
			fi
			export Q_DEBUG=1
			export VERBOSE=1
			"node_modules/.bin/mocha" --reporter list tests/test.js
		popd > /dev/null
	}

	runJSTests

}
init $@